version: '3.3'

services:
    rdtclient:
        image: rogerfar/rdtclient
        container_name: rdtclient
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PUID=1001
            - PGID=1001
        volumes:
            - ${PWD}/data/downloads:/data/downloads
            - ${PWD}/data/db:/data/db
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'
